### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Bluntflame** [rheirman/WhatTheHack#1]
How do I download

**Comment by rheirman** [comment]
Go to []( https://github.com/rheirman/WhatTheHack ), click the green "clone or download" button on the top right. Unzip, and place the folder in the rimworld mods folder.

**Comment by rheirman** [comment]
![image](https://user-images.githubusercontent.com/26927796/43957002-7de38d34-9ca6-11e8-822c-86e4f091664a.png)
