### ISSUE TITLE
{} Has no numeric value

### ISSUE THREAD

**Issue by Proxyer** [rheirman/WhatTheHack#20]
Huge update cheers for good work. So, I found one problem while doing the translation.

Keyed/WhatTheHack_keys.xml line 232
<WTH_RogueAI_Annoyed_Remark_18>{} should be replaced</WTH_RogueAI_Annoyed_Remark_18>

There is no numerical value in {}. Probably, is it {0}?

**Comment by rheirman** [comment]
Whoops, you're right, it should be {0} indeed. I'll change it. Good luck with translating :)
