### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lucas20014545** [rheirman/WhatTheHack#37]
Exception drawing ThingOverlay for WTH_PortableChargingPlatform26161: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.Building_Bed.get_PlayerCanSeeOwners () [0x00006] in <e7ff5a4f38ad429ba34547c6103ee2f5>:0 
  at RimWorld.Building_Bed.DrawGUIOverlay () [0x00018] in <e7ff5a4f38ad429ba34547c6103ee2f5>:0 
  at (wrapper dynamic-method) Verse.ThingOverlays.DMD<DMD<ThingOverlaysOnGUI_Patch1>?844980864::ThingOverlaysOnGUI_Patch1>(Verse.ThingOverlays)
Verse.Log:Error(String, Boolean)
Verse.ThingOverlays:DMD<DMD<ThingOverlaysOnGUI_Patch1>?844980864::ThingOverlaysOnGUI_Patch1>(ThingOverlays)
RimWorld.MapInterface:DMD<DMD<MapInterfaceOnGUI_BeforeMainTabs_Patch2>?1619815808::MapInterfaceOnGUI_BeforeMainTabs_Patch2>(MapInterface)
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

**Comment by rheirman** [comment]
Thanks for reporting, but please put a bit more effort in your report. As stated in the download link: 

*If you find any issues, please report them using the Hugslib report functionality. Describe clearly what happens and how to reproduce it and press ctrl+f12 in-game to get a shareable link of your Hugslib log. Place your report here: https://github.com/rheirman/WhatTheHack/issues
Bug reports without a log are almost always useless.*

**Comment by lucas20014545** [comment]
oh my bad

https://gist.github.com/b7eb776f0761a99da6d8ddbe9ee45b98

When I build these two things in the picture, it will cause this problem.

![LIZ$%0_8B_W9G8V5@%VUQ3C](https://user-images.githubusercontent.com/26396765/77882771-3ea5c900-7294-11ea-84b7-617a74268612.png)

**Comment by lucas20014545** [comment]
and this

https://gist.github.com/b96c5c979b4433ca26a329452b93f2d4

Appears when I click on this
![2 L69M1DP69 TUI}6UCP7Y2](https://user-images.githubusercontent.com/26396765/77884214-37cc8580-7297-11ea-8e2e-83b2bf1e0f15.png)
![{P3_$WQHD$JYSDCZ)324{2](https://user-images.githubusercontent.com/26396765/77884224-3b600c80-7297-11ea-98e8-fd9e178ecd2c.png)

**Comment by rheirman** [comment]
Thanks for reporting. I've fixed these issues in the latest test release: 
https://github.com/rheirman/WhatTheHack/releases/tag/v2.0.1
