### ISSUE TITLE
AI scuffed 

### ISSUE THREAD

**Issue by ShunTheWitch** [rheirman/WhatTheHack#38]
https://gist.github.com/641a02b19796122acf4bbd6884b353ef

Currently it seems all captured mechs are Incapable of all jobs, including violence, cannot manually use them with implanted AI either, this may be a wider issue with my modlist but it would be a good idea to post this here just in case in my opinion, also enemy mech aggro is entirely borked as turrets will start targetting everything around them for split seconds and mechs will not run towards your base once activated.

**Comment by CrazySnapDragon** [comment]
I can confirm that no mod is causing the problem. I just started fresh game with only what the hack. And the lancer I hacked is still incapable of violence 
![20200331040829_1](https://user-images.githubusercontent.com/62919054/77979892-2b334600-7306-11ea-81d2-fb0293059f18.jpg)

**Comment by rimpy-custom** [comment]
Did you activate HugsLib?

**Comment by ShunTheWitch** [comment]
Well considering I had to have hugslib to even post that log, Yes.

**Comment by rheirman** [comment]
Thanks for reporting. I've fixed this issue in the latest test release: 
https://github.com/rheirman/WhatTheHack/releases/tag/v2.0.1
