### ISSUE TITLE
Mechs brought to hacking table dropping/losing weapons

### ISSUE THREAD

**Issue by lukasbryla** [rheirman/WhatTheHack#40]
Hi,
Im experiencing issue when mechs I bring to hacking table instantly either drop their weapon or the weapon vanishes.
As stated in log below, Im using rimworld core, royalty dlc, harmony, hughslib and this test version of What The Hack.
Before i tried it with bare minimum mods I have tested it with Polarisbloc - Mechenemy and their mechs dropped weapons while vanilla mechs weapons vanishes.

The entire issue can be seen on short video I made while testing, uploaded to cloudinary.
** VIDEO LINK -** https://res.cloudinary.com/ddkt4zynz/video/upload/v1585925178/RimWorld_by_Ludeon_Studios_2020-04-03_16-33-28_qmyzmy.mp4

First image is while I was testing with many mods, encountered a mech unable of violence but thats not really the issue. Matrix error happens right?

Second is mech without item.

**LOGS BELOW**

![RimWorld by Ludeon Studios 03 04 2020 16_02_18](https://user-images.githubusercontent.com/47027872/78373000-4635dc80-75ca-11ea-9e22-bc941f162f34.png)
![RimWorld by Ludeon Studios 03 04 2020 16_32_24](https://user-images.githubusercontent.com/47027872/78373029-5057db00-75ca-11ea-9a9b-b5dede260d7a.png)

-
-
**Link for log**
https://gist.github.com/29aa0d9387731b7bcb7d0b6f0c17c375

**Console log**
_
Command line arguments: -quicktest
Verse.Log:Message(String, Boolean)
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

RimWorld 1.1.2589 rev1331
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

Mod Test Mod  is missing packageId in About.xml! (example: <packageId>AuthorName.ModName.Specific</packageId>)
Verse.Log:Warning(String, Boolean)
Verse.ModMetaDataInternal:TryParsePackageId(Boolean, Boolean)
Verse.ModMetaData:Init()
Verse.ModMetaData:.ctor(String, Boolean)
Verse.ModLister:RebuildModList()
Verse.ModLister:.cctor()
Verse.ModsConfig:.cctor()
Verse.LoadedModManager:InitializeMods()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

[HugsLib] version 7.1.4
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.HugsLibController:InitializeController()
HugsLib.HugsLibController:EarlyInitialize()
HugsLib.Core.HugsLibMod:.ctor(ModContentPack)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[])
System.Reflection.MonoCMethod:DoInvoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo)
System.RuntimeType:CreateInstanceImpl(BindingFlags, Binder, Object[], CultureInfo, Object[], StackCrawlMark&)
System.Activator:CreateInstance(Type, BindingFlags, Binder, Object[], CultureInfo, Object[])
System.Activator:CreateInstance(Type, Object[])
Verse.LoadedModManager:CreateModClasses()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Tried to load duplicate UnityEngine.Texture2D with path: FilesystemFile [D:\Steam\steamapps\common\RimWorld\Mods\WhatTheHack-2.0.0\Textures\Things\RogueAI_Preview.psd], Length 104485 and internal path: Things/RogueAI_Preview
Verse.Log:Warning(String, Boolean)
Verse.ModContentHolder`1:ReloadAll()
Verse.ModContentPack:<ReloadContent>b__41_0()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:DMD<DMD<Update_Patch1>?756263808::Update_Patch1>(Root)
Verse.Root_Entry:Update()

[HugsLib] initializing WhatTheHack
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - roolo.whatthehack
Verse.Log:Message(String, Boolean)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Cleaned up 0 depricated records from What the Hack!?
Verse.Log:Message(String, Boolean)
WhatTheHack.Storage.ExtendedDataStorage:Cleanup()
WhatTheHack.Base:WorldLoaded()
HugsLib.HugsLibController:OnPlayingStateEntered()
HugsLib.Patches.Game_FinalizeInit_Patch:WorldLoadedHook()
Verse.Game:DMD<DMD<FinalizeInit_Patch1>?-1014532992::FinalizeInit_Patch1>(Game)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Exception filling tab RimWorld.ITab_Pawn_Character: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) RimWorld.CharacterCardUtility.DMD<DMD<DrawCharacterCard_Patch0>?-1004028544::DrawCharacterCard_Patch0>(UnityEngine.Rect,Verse.Pawn,System.Action,UnityEngine.Rect)
  at RimWorld.ITab_Pawn_Character.FillTab () [0x00033] in <29684bdca4b441d38f64a3f064edc8ed>:0 
  at Verse.InspectTabBase+<>c__DisplayClass14_0.<DoTabGUI>b__0 () [0x00039] in <29684bdca4b441d38f64a3f064edc8ed>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.<>c__DisplayClass14_0:<DoTabGUI>b__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

_

**Comment by rheirman** [comment]
Thanks for reporting. This has been fixed in the new test release: 
https://github.com/rheirman/WhatTheHack/releases/tag/v2.0.1
