### ISSUE TITLE
Mechs losing weapons the second they are downed

### ISSUE THREAD

**Issue by lukasbryla** [rheirman/WhatTheHack#41]
Hi,
I tried WTH 2.0.1 with a quicktest.
Mechs weapons now vanish upon being downed.

https://gist.github.com/f1ae54bcc70d43316578ce3e464da917

Would you like more info or is it sufficient?

**Comment by rheirman** [comment]
Somehow I missed this due to some local changes. Thanks for the report. It's fixed now in the latest test release: 
https://github.com/rheirman/WhatTheHack/releases/tag/v2.0.2
